### ISSUE TITLE
Private DNS QS Tile

### ISSUE THREAD

**Issue by DeanWinchesterrr** [rahaaatul/automate-flows#1]
06-16 13:33:55.150 F 20@2: java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

**Comment by rahaaatul** [comment]
> 06-16 13:33:55.150 F 20@2: java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

You have to give automate write secure settings permission via ADB.

![Screenshot_20240616_141503](https://github.com/rahaaatul/automate-flows/assets/86149861/4e591173-b573-4fb4-8967-4e3620d84b34)

**Comment by DeanWinchesterrr** [comment]
> > 06-16 13:33:55.150 F 20@2: java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
> 
> You have to give automate write secure settings permission via ADB.
> 
> ![Screenshot_20240616_141503](https://private-user-images.githubusercontent.com/86149861/340075025-4e591173-b573-4fb4-8967-4e3620d84b34.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjYxOTQsIm5iZiI6MTcxODUyNTg5NCwicGF0aCI6Ii84NjE0OTg2MS8zNDAwNzUwMjUtNGU1OTExNzMtYjU3My00ZmI0LTg5NjctNGUzNjIwZDg0YjM0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA4MTgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZDgzNGU2MDk4NTQ3ZWM5Njk0ZGJlMDMyMWFmZWY1MzRjNWZkMzBlZGY1MjhhZmI3OWE2MjIxZjU5NzBjMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0BAREJqvRHaUQjk64TykPqevnF-FN7HtaYBmv6fYuRA)

06-16 13:51:02.380 I 23@3: Quick Settings tile show
06-16 13:51:05.525 I 23@11: Expression true?
06-16 13:51:05.525 I 23@8: Expression true?
06-16 13:51:05.526 I 23@10: Expression true?
06-16 13:51:05.526 I 23@4: System setting set
06-16 13:51:05.529 F 23@4: android.os.RemoteException: Remote stack trace:
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2561)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1562)
	at com.android.providers.settings.SettingsProvider.insertGlobalSetting(SettingsProvider.java:1516)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:495)
	at android.content.ContentProvider.call(ContentProvider.java:2548)

06-16 13:51:05.530 I 23@4: Stopped by failure

**Comment by DeanWinchesterrr** [comment]
06-16 13:54:01.828 I 24@15: App start
06-16 13:54:01.835 F 24@15: com.llamalab.automate.access.AccessNotGrantedException: com.llamalab.automate.access.DrawOverlayAccessControl@ca03110
06-16 13:54:01.836 I 24@15: Stopped by failure

**Comment by rahaaatul** [comment]
Did you give all permissions needed for the flow?

![Screenshot_2024_0616_142618](https://github.com/rahaaatul/automate-flows/assets/86149861/ceba2759-31ce-4bc4-b4cb-a5e750f6a461)

**Comment by DeanWinchesterrr** [comment]
First error fixed after giving write secure settings permission via ADB (shizuTools)

Second error only happens when you long press the qs tile

Other than that it's working PERFECTLY FINE.

**Comment by rahaaatul** [comment]
> Second error only happens when you long press the qs tile

Well, that's a problem, it should open up the network settings window, where the private DNS option is.

Can you recheck after giving all permission needed for the flow?

**Comment by DeanWinchesterrr** [comment]
> > Second error only happens when you long press the qs tile
> 
> Well, that's a problem, it should open up the network settings window, where the private DNS option is.
> 
> Can you recheck after giving all permission needed for the flow?

Second error fixed after giving "appear on top" permission. So dumb. Sorry man. It's literally flawless and it's me who couldn't configure it properly.

So what I've gathered 

1. Perform
pm grant com.llamalab.automate android.permission.WRITE_SECURE_SETTINGS

2. Give ALL the permissions before starting 

And that's it !!!

**Comment by DeanWinchesterrr** [comment]
![IMG_20240616_140627](https://github.com/rahaaatul/automate-flows/assets/95219257/aca5745e-5dca-4887-a368-85ef0007717c)
Long Press Now opens this, if you were curious.

**Comment by rahaaatul** [comment]
> ![IMG_20240616_140627](https://private-user-images.githubusercontent.com/95219257/340077341-aca5745e-5dca-4887-a368-85ef0007717c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjczNDYsIm5iZiI6MTcxODUyNzA0NiwicGF0aCI6Ii85NTIxOTI1Ny8zNDAwNzczNDEtYWNhNTc0NWUtNWRjYS00ODg3LWEzNjgtODVlZjAwMDc3MTdjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA4MzcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YmY3OGZkMTc1YjI0NzNkMDFlNjY3MmNmYzFhMjYwZmJhNTdjOTllM2ZkNzBjNDc4OTJkMTQ3NjQxYTY2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.51lkeghuX1L8n8GPlxFPmeuvrJq7ranOLy_V0Zsg8I8) Long Press qs tile Now opens this, if you were curious.

Where's your private DNS located? I don't see the option in the screenshot.

**Comment by DeanWinchesterrr** [comment]
![Screenshot_2024-06-16-14-12-21-74_41a74ddf68be21faad2fbbb691b15143](https://github.com/rahaaatul/automate-flows/assets/95219257/63272016-31b7-4791-bc66-3abe91faeeb6)
I have to go inside connection and sharing

**Comment by rahaaatul** [comment]
Well, it's better than nothing. I can't add device specific settings windows, have to go with a default one.

Thanks for sharing the screenshots.
