### ISSUE TITLE
🐛 android.security.KeyChainException: Certificate or private key inaccessible: Automate

### ISSUE THREAD

**Issue by DeanWinchesterrr** [rahaaatul/automate-flows#2]
Very sorry to have come back here

06-16 21:46:30.080 I 22@5: Network service discover
06-16 21:46:33.094 I 22@15: Expression true?
06-16 21:46:33.096 I 22@12: Failure catch
06-16 21:46:33.096 I 22@6: ADB protocol set
06-16 21:46:33.126 F 22@6: android.security.KeyChainException: Certificate or private key inaccessible: Automate
06-16 21:46:33.137 I 22@16: System setting set
06-16 21:46:33.139 I 22@17: Delay
06-16 21:46:34.147 I 22@4: System setting set
06-16 21:46:34.150 I 22@5: Network service discover
06-16 21:46:35.546 I 22@5: Stopped by user

Please help me with this. The automate app setup works but shizuku doesn't

**Comment by rahaaatul** [comment]
> Very sorry to have come back here

Don't worry about it.

> 06-16 21:46:33.126 F 22@6: android.security.KeyChainException: Certificate or private key inaccessible: Automate 

Did you follow the instructions [here](https://github.com/rahaaatul/automate-flows/tree/main/Auto%20ADB%20Mode)?

Looks like you need to generate key before running the flow.

**Comment by DeanWinchesterrr** [comment]
I don't know "how" to generate key, or what "key" is, could you help?

**Comment by rahaaatul** [comment]
> I don't know "how" to generate key, or what "key" is, could you help?

Read **[The Setup](https://llamalab.com/automate/doc/block/adb_shell_command.html)**.

**Comment by DeanWinchesterrr** [comment]
> > I don't know "how" to generate key, or what "key" is, could you help?
> 
> Read **[The Setup](https://llamalab.com/automate/doc/block/adb_shell_command.html)**.

![Screenshot_2024-06-18-20-10-44-77_e6a78a44c2a4240c0ee4570124bdc575](https://github.com/rahaaatul/automate-flows/assets/95219257/b8b4d4dd-0d59-4615-b367-a03894535d42)

See i didn't know this is what you meant

**Comment by rahaaatul** [comment]
You haven't read the setup section, read it, you'll find the answer.

In the flow:
1. Tap ADB shell command block.
2. Tap `INSTALL GENERATED KEY`
3. Name the key `Automate`.

**Comment by DeanWinchesterrr** [comment]
After clicking on Install Generated Certificate

![Uploading Screenshot_2024-06-19-09-31-42-25_41a74ddf68be21faad2fbbb691b15143.jpg…]()

**Comment by DeanWinchesterrr** [comment]
06-19 09:34:17.970 I 62@1: Flow beginning
06-19 09:34:17.973 I 62@10: Wi-Fi network connected?
06-19 09:34:17.989 I 62@4: System setting set
06-19 09:34:17.999 I 62@5: Network service discover
06-19 09:34:21.017 I 62@15: Expression true?
06-19 09:34:21.018 I 62@12: Failure catch
06-19 09:34:21.019 I 62@6: ADB protocol set
06-19 09:34:21.147 F 62@6: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
06-19 09:34:21.174 I 62@16: System setting set
06-19 09:34:21.178 I 62@17: Delay
06-19 09:34:22.187 I 62@4: System setting set
06-19 09:34:22.191 I 62@5: Network service discover
06-19 09:34:23.693 I 62@5: Stopped by user

**Comment by DeanWinchesterrr** [comment]
https://llamalab.com/automate/community/flows/48295

Maybe it's happening because I'm using an overlapping module which also used port 5555

**Comment by rahaaatul** [comment]
> https://llamalab.com/automate/community/flows/48295
> 
> Maybe it's happening because I'm using an overlapping module which also uses port 5555

Restart the device, and see if it works.

**Comment by Unstepbystep** [comment]
![adb](https://github.com/rahaaatul/automate-flows/assets/173249262/560333ed-5fa8-445a-afee-46fd61b95b40)

**Comment by rahaaatul** [comment]
> ![adb](https://private-user-images.githubusercontent.com/173249262/341851219-560333ed-5fa8-445a-afee-46fd61b95b40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5OTMzNDksIm5iZiI6MTcxODk5MzA0OSwicGF0aCI6Ii8xNzMyNDkyNjIvMzQxODUxMjE5LTU2MDMzM2VkLTVmYTgtNDQ1YS1hZmVlLTQ2ZmQ2MWI5NWI0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxODA0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjU4ZDhkZDE0MjhlMWEwZDUzZDAxZTE2MDM2NDhkMjExMmJjYzVkYzM4ZTcwN2ZiZDM2OTM0ZTc0OGY0ODYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i6KV8D9oJwbmkToQBW1SLxnq503vjoLjnbO9O7NRyIQ)

1. Open Automate settings
2. Forget Privileged service ADB keys.
3. Privileged service start method > Android Debug Bridge
4. Pair Automate.

**Comment by rahaaatul** [comment]
@Unstepbystep #3

**Comment by joeyoropesa-dev** [comment]
Is there any free alternatives that doesn't require for adb wireless connection certificate to be installed, that supports automated tasks to automatically turn on wireless adb and doesn't require root nor PC access everytime device reboots.

If anyone knows alternative that meets these requirements, I could implement setup with Family Link and child's device that will fulfill enterprise requirements without needing to pay anything, completely free. VPN ZeroTier One completes the rest of my wanted setup.


Also it can help if there is an bypass method via adb to install user certificate Automate (keypair private+public key) on device where Parental Control is activated by Family Link and doesn't require root access to write into that folder for user certificates.
