### ISSUE TITLE
🐛 Pairing failed: isConnected failed: ECONNREFUSED (Connection refused)

### ISSUE THREAD

**Issue by rahaaatul** [rahaaatul/automate-flows#3]
![adb](https://github.com/rahaaatul/automate-flows/assets/173249262/560333ed-5fa8-445a-afee-46fd61b95b40)

**Comment by rahaaatul** [comment]
Try this:

1. Open Automate settings
2. Forget Privileged service ADB keys.
3. Privileged service start method > Android Debug Bridge
4. Pair Automate.

**Comment by Unstepbystep** [comment]
(Note: After step 2 above, it was necessary to reset the device.)

New error:

06-21 23:45:37.233 I 422231@6: ADB protocol set

06-21 23:45:37.458 F 422231@6: javax.net.ssl.SSLProtocolException: Read error: ssl=0xb400007078395918: Failure in SSL library, usually a protocol error
error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/tls_record.cc:592 0xb400006f783dfa40:0x00000003)

**Comment by rahaaatul** [comment]
> (Note: After step 2 above, it was necessary to reset the device.)
> 
> New error:
> 
> 06-21 23:45:37.233 I 422231@6: ADB protocol set
> 
> 06-21 23:45:37.458 F 422231@6: javax.net.ssl.SSLProtocolException: Read error: ssl=0xb400007078395918: Failure in SSL library, usually a protocol error error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/tls_record.cc:592 0xb400006f783dfa40:0x00000003)

Generate a key, and set it. Look at [troubleshooting](https://github.com/rahaaatul/automate-flows/tree/main/Auto%20ADB%20Mode#troubleshooting) section and look for suffixes, you'll find the fixes.

**Comment by Unstepbystep** [comment]
Flow works when the device is restarted and paired.  However, after Shizuku is manually terminated, the flow gives an error when it is run again.  It is necessary to restart the device and pair it.  But this method does not always work.  So the flow does not work stably.

**Comment by rahaaatul** [comment]
> Flow works when the device is restarted and paired. 

As intended.

> However, after Shizuku is manually terminated, the flow gives an error when it is run again. 

This flow was designed to run only once. I don't know why you have to restart the flow again. It already set TCP to 5555. Now when you press start on shizuku, you can select 5555, and it will run again.

> It is necessary to restart the device and pair it. 

No, paring process is only time thing. Seems like a device issue to me.

> But this method does not always work. So the flow does not work stably.

Flow works perfectly fine. I'm running it on my device for over a week now.

You need to check your device settings.

**Comment by Unstepbystep** [comment]
Hi again,

I rearranged 
[Shizuku batch start.zip](https://github.com/user-attachments/files/15944925/Shizuku.batch.start.zip)
Flow to work the way I wanted.  So I can run Shizuku with a single click only when I need it.  This prevents the device's resources from being used in vain and positively affects its performance.  I put important explanations about Flow in Turkish. Thanks 'Rahat Gazi'.

**Comment by rahaaatul** [comment]
> Hi again,
> 
> I rearranged [Shizuku batch start.zip](https://github.com/user-attachments/files/15944925/Shizuku.batch.start.zip) Flow to work the way I wanted. So I can run Shizuku with a single click only when I need it. 

Glad to hear that.

> This prevents the device's resources from being used in vain and positively affects its performance. 

Does shizuku really use that many resources? I keep it running, I don't see any issue.

> I put important explanations about Flow in Turkish. Thanks 'Rahat Gazi'.

Nice, you should translate it in English and share it on automate community, should if anyone else need it.

By the way, did the `isConnected failed` issue resolve?
