### ISSUE TITLE
android.os.RemoteException: Remote stack trace

### ISSUE THREAD

**Issue by francois072** [rahaaatul/automate-flows#4]
Keep getting this error on Samsung:

`07-18 02:05:53.452 I 49@1: Flow beginning
07-18 02:05:53.453 I 49@10: Wi-Fi network connected?
07-18 02:05:53.483 I 49@4: System setting set
07-18 02:05:53.486 F 49@4: android.os.RemoteException: Remote stack trace:
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2945)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:2008)
	at com.android.providers.settings.SettingsProvider.insertGlobalSetting(SettingsProvider.java:1962)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:607)
	at android.content.ContentProvider.call(ContentProvider.java:2582)

07-18 02:05:53.487 I 49@4: Stopped by failure`

**Comment by rahaaatul** [comment]
Can you be more specific?

- What Android OS version?
- What Automate version?
- Which flow are you using?

At a glance, it's a failing after setting a system setting. Probably that setting does not exist or have a different name.

**Comment by simonmanuel** [comment]
I have the same issue.

OS: ColorOS 14.0 (Android 14)
Automate: Version 1.43.1
Flow: Auto ADB over TCPIP + Shizuku

**Comment by Oli-70** [comment]
I have the same issue too.

OS: Nothing OS 2.6 (Android 14)
Automate: Version 1.43.1
Flow: Auto ADB over TCPIP + Shizuku and Auto ADB over TCPIP (both don't work)

**Comment by rahaaatul** [comment]
Can you guys confirm if you gave `modify system settings` permission to Automate?

@simonmanuel @francois072 @Oli-70

**Comment by Oli-70** [comment]
![Screenshot_20240729-220654.png](https://github.com/user-attachments/assets/0cc372a9-c6dd-4eea-8da8-2f386033e581)

Yes, it is enabled.

**Comment by simonmanuel** [comment]
> Can you guys confirm if you gave `modify system settings` permission to Automate?
> 
> @simonmanuel @francois072 @Oli-70


It was on. Looked to see if there are other privileges that were unchecked using your hint. 

`modify secure system settings` was not checked/turned on. Turned it on and the previous error disappeared and it's moving past to the end.

Only error now is `android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)` which I believe is easier to fix.

Thanks

**Comment by rahaaatul** [comment]
> ![Screenshot_20240729-220654.png](https://private-user-images.githubusercontent.com/176917295/353221323-0cc372a9-c6dd-4eea-8da8-2f386033e581.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyODU4NTYsIm5iZiI6MTcyMjI4NTU1NiwicGF0aCI6Ii8xNzY5MTcyOTUvMzUzMjIxMzIzLTBjYzM3MmE5LWM2ZGQtNGVlYS04ZGE4LTJmMzg2MDMzZTU4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQyMDM5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTVlNTJjMjZlN2FhNTliOGI4YmFkOGNjNGI1YWM5MTJlMTc3ZGUzMjAwMmI2MjRjMzA4MjY5Y2NjMDVlMTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DesHyxZYORPwp3GGgBRNBw1Jhks4Jm2nHrG_NPOXTdg)
> 
> Yes, it is enabled.

Not this, `modify secure system settings`. Refer to configuration in [the wiki](https://github.com/rahaaatul/automate-flows/tree/main/Auto%20ADB%20Mode#configuration).

**Comment by rahaaatul** [comment]
> Only error now is `android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)` which I believe is easier to fix.

Check troubleshooting in the [wiki](https://github.com/rahaaatul/automate-flows/tree/main/Auto%20ADB%20Mode#troubleshooting).

**Comment by rahaaatul** [comment]
@francois072 you probably didn't gave Automate the `modify secure system settings` permission.

Read how to enable it [here](https://llamalab.com/automate/doc/adb.html).

I'm closing this issue for now, if it wasn't the solution for you, feel free to reopen the issue again.

**Comment by Oli-70** [comment]
It worked for me too. Now I only get: "android.security.KeyChainException: Certificate or private key inaccessible: Automate"

The Wikis say: "Install Generated Key, then add it to Keychain alias."

Does anyone know a good tutorial or instruction for that?

**Comment by rahaaatul** [comment]
> It worked for me too. Now I only get: "android.security.KeyChainException: Certificate or private key inaccessible: Automate"
> 
> The Wikis say: "Install Generated Key, then add it to Keychain alias."
> 
> Does anyone know a good tutorial or instruction for that?

Read [ADB shell command](https://llamalab.com/automate/doc/block/adb_shell_command.html) Wiki.

**Comment by Oli-70** [comment]
Hello, I've read through the Wiki, but I still don't understand how to create a key or what to do with it. Could you walk me through setting up steps 1 and 2? My technical knowledge is quite basic, and I wasn't able to figure it out on my own. A detailed, step-by-step guide would be incredibly helpful. Thanks a lot!

**Comment by rahaaatul** [comment]
> Hello, I've read through the Wiki, but I still don't understand how to create a key or what to do with it. Could you walk me through setting up steps 1 and 2? My technical knowledge is quite basic, and I wasn't able to figure it out on my own. A detailed, step-by-step guide would be incredibly helpful. Thanks a lot!

Hi. I've updated the [wiki](https://github.com/rahaaatul/automate-flows/wiki/Auto-ADB-Mode#installing-generated-key), you may want to read that.
