### ISSUE TITLE
Auto ADB over TCPIP + Shizuku: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)

### ISSUE THREAD

**Issue by Xisrr1** [rahaaatul/automate-flows#8]
### What happened?

I followed the guide, but when I start the flow it just loops and shows this error: `android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)`.

I've tried the troubleshooting methods, but they didn't work. Automate 1.43.2

### Flow

Auto ADB + Shizuku

### Android Version

Android 14

### Automate Version

1.43.1

### Relevant log output

```shell
09-08 18:54:22.857 I 3@16: System setting set
09-08 18:54:22.861 I 3@17: Delay
09-08 18:54:23.872 I 3@4: System setting set
09-08 18:54:23.882 I 3@5: Network service discover
09-08 18:54:26.897 I 3@15: Expression true?
09-08 18:54:26.898 I 3@12: Failure catch
09-08 18:54:26.899 I 3@6: ADB protocol set
09-08 18:54:26.972 F 3@6: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
```

**Comment by rahaaatul** [comment]
1. Try Forget privileged service ADB keys in Automate Settings under Privileged & Superuser.
2. Restart the device.
3. [Pair again](https://github.com/rahaaatul/automate-flows/wiki/Auto-ADB-Mode#pairing-automate).
4. Run the flow.

> [!NOTE]
> If the above solution does not work. Report issue in [Automate's subreddit.](https://www.reddit.com/r/AutomateUser).

**Comment by Xisrr1** [comment]
I'll report back in a few minutes.

**Comment by Xisrr1** [comment]
> 1. Try Forget privileged service ADB keys in Automate Settings under Privileged & Superuser.
> 2. Restart the device.
> 3. [Pair again](https://github.com/rahaaatul/automate-flows/wiki/Auto-ADB-Mode#pairing-automate).
> 4. Run the flow.

This didn't work, I get the same error.
What should I report in the subreddit? I am new to Automate.

**Comment by rahaaatul** [comment]
> > 1. Try Forget privileged service ADB keys in Automate Settings under Privileged & Superuser.
> > 2. Restart the device.
> > 3. [Pair again](https://github.com/rahaaatul/automate-flows/wiki/Auto-ADB-Mode#pairing-automate).
> > 4. Run the flow.
> 
> This didn't work, I get the same error. 

- Did you generate a key though?
- Do you have shizuku installed and running?

> What should I report in the subreddit? I am new to Automate.

Write the error `Shizuku: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused) on Andorid 14` in your case.

and then link to the flow.

**Comment by Xisrr1** [comment]
> * Did you generate a key though?

This? Yes
![Screenshot_20240908_203347_Automate](https://github.com/user-attachments/assets/6369687d-a3b5-45ac-8f57-7a3fcf32af62)

> * Do you have shizuku installed?

Yes

**Comment by rahaaatul** [comment]
can you connect `block 15`s `yes` to `7` and `7`s ok to `12` and run the flow again? 

and share the log here.

**Comment by rahaaatul** [comment]
> > * Did you generate a key though?
> 
> This? Yes ![Screenshot_20240908_203347_Automate](https://private-user-images.githubusercontent.com/133952156/365456293-6369687d-a3b5-45ac-8f57-7a3fcf32af62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTcyNDIsIm5iZiI6MTcyNTgxNjk0MiwicGF0aCI6Ii8xMzM5NTIxNTYvMzY1NDU2MjkzLTYzNjk2ODdkLWEzYjUtNDVhYy04ZjU3LTdhM2ZjZjMyYWY2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNzM1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjQwYWViODY3ZDM3YTMyYzc2NDczMDRhNDIyYzIzMWNiMjkwNTk4NTk2OWEwNjE0NDRjOTcwMjRkODAyNGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ts8qVbFYWRTB6xwqzAqybxtS0Gu8Fk8F_j5gxBZXl3s)

Did you add the generated keychain to keychain alias?

**Comment by Xisrr1** [comment]
> > > * Did you generate a key though?
> > 
> > 
> > This? Yes ![Screenshot_20240908_203347_Automate](https://private-user-images.githubusercontent.com/133952156/365456293-6369687d-a3b5-45ac-8f57-7a3fcf32af62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTcyNDIsIm5iZiI6MTcyNTgxNjk0MiwicGF0aCI6Ii8xMzM5NTIxNTYvMzY1NDU2MjkzLTYzNjk2ODdkLWEzYjUtNDVhYy04ZjU3LTdhM2ZjZjMyYWY2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNzM1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjQwYWViODY3ZDM3YTMyYzc2NDczMDRhNDIyYzIzMWNiMjkwNTk4NTk2OWEwNjE0NDRjOTcwMjRkODAyNGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ts8qVbFYWRTB6xwqzAqybxtS0Gu8Fk8F_j5gxBZXl3s)
> 
> Did you add the generated keychain to keychain alias?

Yes

**Comment by Xisrr1** [comment]
> can you connect `block 15`s `yes` to `7` and `7`s ok to `12` and run the flow again?
> 
> and share the log here.

`09-08 20:47:24.224 I 5@1: Flow beginning
09-08 20:47:24.230 I 5@10: Wi-Fi network connected?
09-08 20:47:24.284 I 5@4: System setting set
09-08 20:47:24.289 I 5@5: Network service discover
09-08 20:47:27.315 I 5@15: Expression true?
09-08 20:47:27.317 U 5@7: 

Name: adb-RZCT921BX0X-QYM51y
Host: 192.168.1.141
Port: 34235

09-08 20:47:27.318 I 5@12: Failure catch
09-08 20:47:27.321 I 5@6: ADB protocol set
09-08 20:47:27.550 F 5@6: javax.net.ssl.SSLProtocolException: Read error: ssl=0xb40000798c657798: Failure in SSL library, usually a protocol error
error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/tls_record.cc:592 0xb400007a3c6d5ce0:0x00000003)`

**Comment by Xisrr1** [comment]
> Okay, can you turn off wireless debugging, open shizuku app, stop it from running, and start again. 

Done

> See if `5555` option appears or not.

Where?

**Comment by rahaaatul** [comment]
> 09-08 20:47:27.318 I 5@12: Failure catch 09-08 20:47:27.321 I 5@6: ADB protocol set 09-08 20:47:27.550 F 5@6: javax.net.ssl.SSLProtocolException: Read error: ssl=0xb40000798c657798: Failure in SSL library, usually a protocol error error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/tls_record.cc:592 0xb400007a3c6d5ce0:0x00000003)`

New error, but falls in the same category. **Pairing Issue**.
You need to go to wireless debugging and manually remove automate pairings. and try pairing again from the app.

**Comment by rahaaatul** [comment]
> > Okay, can you turn off wireless debugging, open shizuku app, stop it from running, and start again.
> 
> Done
> 
> > See if `5555` option appears or not.
> 
> Where?

It'll show something like this in shizuku:
![Screenshot_2024_0908_235416](https://github.com/user-attachments/assets/442d83bc-378b-4e65-89bb-95e4fbe31dd7)

**Comment by Xisrr1** [comment]
> New error, but falls in the same category. **Pairing Issue**. You need to go to wireless debugging and manually remove automate pairings. and try pairing again from the app.

I did that a few times, no luck. I've seen someone with the same issue recently [Here](https://www.reddit.com/r/AutomateUser/s/iYIa35yu4g), but I didn't find a solution yet.

**Comment by Xisrr1** [comment]
> > > Okay, can you turn off wireless debugging, open shizuku app, stop it from running, and start again.
> > 
> > 
> > Done
> > > See if `5555` option appears or not.
> > 
> > 
> > Where?
> 
> It'll show something like this in shizuku: ![Screenshot_2024_0908_235416](https://private-user-images.githubusercontent.com/86149861/365457370-442d83bc-378b-4e65-89bb-95e4fbe31dd7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTg0NDEsIm5iZiI6MTcyNTgxODE0MSwicGF0aCI6Ii84NjE0OTg2MS8zNjU0NTczNzAtNDQyZDgzYmMtMzc4Yi00ZTY1LTg5YmItOTVlNGZiZTMxZGQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE3NTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZWYyMDhiMDE1MWI5NjlmMzg5YWY3M2M3MmMyN2IyMDEzNzFkNzdiNGFiY2JmOGM3NDBkNzJkNzRmMWViODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X0_uJhH09m_BYQPx9rDePeghT2nuLCJcbH7sO_-arIU)

Looks like this for me.
![Screenshot_20240908_205752_Shizuku](https://github.com/user-attachments/assets/36d328de-93e6-427a-a94a-e9f5dc89024f)

**Comment by rahaaatul** [comment]
1. Open developer options on your phone's settings.
1.1. Revoke USB debugging authorizations.
2. Go to security settings > encryption & credentials > user credentials
2.1. Delete all credentials created by automate.
3. Follow the installation wiki again.
4. Don't start the flow. Go to automate settings.
4.1. Restart Adb in tcp/ip mode.

Report back if it worked or not. If it works, run the flow, it should work.

**Comment by Xisrr1** [comment]
> 1. Open developer options on your phone's settings.
>    1.1. Revoke USB debugging authorizations.
> 2. Go to security settings > encryption & credentials > user credentials
>    2.1. Delete all credentials created by automate.
> 3. Follow the installation wiki again.
> 4. Don't start the flow. Go to automate settings.
>    4.1. Restart Adb in tcp/ip mode.
> 
> Report back if it worked or not. If it works, run the flow, it should work.

With the blocks you told me to change in https://github.com/rahaaatul/automate-flows/issues/8#issuecomment-2336765545?

**Comment by rahaaatul** [comment]
> With the blocks you told me to change in [#8 (comment)](https://github.com/rahaaatul/automate-flows/issues/8#issuecomment-2336765545)?

Pair from automate settings, and generate from one of the block.

**Comment by Xisrr1** [comment]
> Report back if it worked or not. If it works, run the flow, it should work.

What works? The restart ADB?

**Comment by rahaaatul** [comment]
> > Report back if it worked or not. If it works, run the flow, it should work.
> 
> What works? The restart ADB?

Restart Adb in tcp/ip mode

**Comment by Xisrr1** [comment]
>    4.1. Restart Adb in tcp/ip mode.

This is what I see 

https://github.com/user-attachments/assets/abef270c-11cb-42c3-b0fb-f923d5e60a7a


> 
> Report back if it worked or not. If it works, run the flow, it should work.

**Comment by rahaaatul** [comment]
No notifications?

Try starting the flow.

**Comment by Xisrr1** [comment]
> No notifications?
> 
> Try starting the flow.

Same error. Just looping.

**Comment by Xisrr1** [comment]
Maybe I debloated a system app that is important for this?

**Comment by rahaaatul** [comment]
> Same error. Just looping.
share the log.

> Maybe I debloated a system app that is important for this?
with root? what app?

**Comment by Xisrr1** [comment]
> share the log.

`09-08 21:24:31.139 I 8@1: Flow beginning
09-08 21:24:31.144 I 8@10: Wi-Fi network connected?
09-08 21:24:31.160 I 8@4: System setting set
09-08 21:24:31.170 I 8@5: Network service discover
09-08 21:24:34.196 I 8@15: Expression true?
09-08 21:24:34.205 I 8@12: Failure catch
09-08 21:24:34.213 I 8@6: ADB protocol set
09-08 21:24:34.606 F 8@6: javax.net.ssl.SSLProtocolException: Read error: ssl=0xb40000798c658b18: Failure in SSL library, usually a protocol error
error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/tls_record.cc:592 0xb400007a3c69e150:0x00000003)
09-08 21:24:34.623 I 8@16: System setting set
09-08 21:24:34.632 I 8@17: Delay
09-08 21:24:35.642 I 8@4: System setting set
09-08 21:24:35.648 I 8@5: Network service discover
09-08 21:24:38.655 I 8@15: Expression true?
09-08 21:24:38.657 I 8@12: Failure catch
09-08 21:24:38.659 I 8@6: ADB protocol set
09-08 21:24:38.707 F 8@6: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)`
> 
> > Maybe I debloated a system app that is important for this?
> 
> with root? what app?

I don't have root, with ADB. [Inure](https://github.com/Hamza417/Inure)

**Comment by Xisrr1** [comment]
Don't mnow if it helps, but now I do have a 555 button in Shizuku. (Shizuku is unpaired from the process you told me to do)
![Screenshot_20240908_213719_Shizuku](https://github.com/user-attachments/assets/d11031d8-b404-437b-91b0-3fa3413c2139)
![Screenshot_20240908_213825_Shizuku](https://github.com/user-attachments/assets/0ecc6da2-f33f-4db6-8352-fb40ca519f56)

**Comment by rahaaatul** [comment]
great it should work now

**Comment by Xisrr1** [comment]
How do I connect with 555? If I click the 555 button, it will show the second screenshot. If I press the Shizuku start button with Wireless debugging on, it will immediately try to connect from that, without letting me choose 555.

**Comment by rahaaatul** [comment]
Do you have a PC?

Can you try `adb tcpip 5555` via usb?

**Comment by rahaaatul** [comment]
> How do I connect with 555? If I click the 555 button, it will show the second screenshot. If I press the Shizuku start button with Wireless debugging on, it will immediately try to connect from that, without letting me choose 555.

are you sure you clicked on `5555`? because it should say something like `info: start.sh begin` at the beginning.

**Comment by Xisrr1** [comment]
> Do you have a PC?
> 
> Can you try `adb tcpip 5555` via usb?

I'll check if i can

**Comment by Xisrr1** [comment]
Okay it did work with the PC, I started Shizuku with 5555. What now? The flow still doesn't work if that's what's supposed to happen.

**Comment by rahaaatul** [comment]
it confirms that it's an wireless debugging issue. since automate is using wireless debugging to set 5555; it won't work. you need to disable those network blocks to automate it; but that's not the purpose of the flow, it was to automate the whole process without human intervention.

You need to figure out why wireless debugging is not working. perhaps try resetting the device.
